<a href="https://colab.research.google.com/github/rswatsch/MAT421_RyanS/blob/main/Homework4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MAT 421 Homework #4
**1.1 Introduction to Linear Equations**

***What is Linear Algebra?***

Linear algebra is a branch of mathematics that focuses entirely on the study of linear equations in different dimensions. One example would be three dimensional Euclidean space.

Additionally, Linear algrebra is used in many careers and fields till this day such as data science and machine learning.

***Important things to know, definitions and Variables.***

Sets - A set is a collection of objects {}

Union - A U B - A set including all elements of A and B

Intersect - A n B - A set including all elements that belong to A & B

Naturals - N = {1,2,3,4,..}

Wholes - W = N U {0}

Integers - Z = W U {-1,-2,-3,...}

Rationals - Q = { p/g : p ∊ Z , q ∊ Z \ {0}}

Irrationals - I = A set of real numbers that are not expressible as fractions of integers

Reals - R = Q U I

Complex Numbers - C = {a + bi: a, b ∊ R, i = sqrt(-1) }

***What is a vector?***

In simple terms it is a a combination of both a magnitude and a direction.

Below is an example of how to create a vector using python.

In [13]:
import numpy as np
vector_row = np.array([[2, -15, 8, 6, 1]])
vector_column = np.array([[1],[2],[3],[4]])

print(vector_row.shape)
print(vector_column.shape)


(1, 5)
(4, 1)


Above is the layout of each row and column and below is how it would look in vector form.

In [14]:
print(vector_row)
print(vector_column)

[[  2 -15   8   6   1]]
[[1]
 [2]
 [3]
 [4]]


There is a way to represent a more than 1,2 dimensional system and that is typically done using Matrix's.

Below is an example of how to design a matrix in python, and acquire it's determinant and other features like an identity matrix.

In [4]:
from numpy.linalg import det

M = np.array([[1,2,6,-1],
              [1,8,4,4],
              [8,0,4,8],
              [2,4,6,10]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[ 1  2  6 -1]
 [ 1  8  4  4]
 [ 8  0  4  8]
 [ 2  4  6 10]]
Determinant: -2496.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[ 1.  2.  6. -1.]
 [ 1.  8.  4.  4.]
 [ 8.  0.  4.  8.]
 [ 2.  4.  6. 10.]]


Matrixes are extremely useful for solving complex linear systems and also for other mathematical systems such as differential equations.

**1.2 Elements of Linear Equations**

There are a multitude of methods of combining and creating new vectors and matrixes from given data below will demonstrate some of those methods.



Using Python to solve a cross-product question.

In [16]:
import numpy as np
x = np.array([[5, 1, -4]])
z = np.array([[-1, 10, 3]])
print(np.cross(x, z))

[[ 43 -11  51]]


**Orthonomal Bases**

Below is a demonstration of how to compute eigenvalues and eigenvectors using python.

In [19]:
import numpy as np
from numpy.linalg import eig

h = np.array([[3, -2, 8],
        [-1, 7, 3],
        [5, 9, 1]])
w,v=eig(h)
print('E-value:', w)
print('E-vector', v)

E-value: [-6.2852346   6.62939123 10.65584337]
E-vector [[ 0.66370166  0.89693545  0.61263883]
 [ 0.21194418 -0.28896184  0.39445046]
 [-0.71734216  0.33467575  0.68489598]]


**1.3 Linear Regression**

Something all of us have heard of and used in STEM and any data based courses. The reason linear regression models are simpler to fit and use are because unknown parameters are essentially converted into only one unknown. The only thing that must be certain and accurate are the assumption that one makes prior to preforming a linear regression.

Below will be an example of a QR decomposition

In [18]:
import numpy as np
from numpy.linalg import qr
x = np.array([[1, 9], [2, 5]])

Q,R = qr(x)
print('Q:', Q)
print('R:', R)

z = np.dot(Q, R)
print('QR:', z)

Q: [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
R: [[-2.23606798 -8.49705831]
 [ 0.         -5.81377674]]
QR: [[1. 9.]
 [2. 5.]]


QR decomposition is an iterative method to find all the eigenvalues of a matrix. It can also find the eigenvectors, but cannot do this simultaneously.